[package]
name = "cfmt"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2.0", default-features = false, features = ["parsing", "full", "extra-traits"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
colored = "3.0"
monostate = "0.1"
